// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdkornpmgusbxsnxcmub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impka29ybnBtZ3VzYnhzbnhjbXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTM1NDMsImV4cCI6MjA3Mjg4OTU0M30.r1gQyW-5PAc2RN617oiKhzMTdDCx1LztP-9mh3Xbqvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});